apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <html>
    <head><title>K8s Observability Platform</title></head>
    <body>
    <h1>Day 2: Services & ConfigMaps</h1>
    <p>Running on Kubernetes via declarative YAML.</p>
    <p>Built by Sri Harsha for SRE transition.</p>
    </body>
    </html>
